services:
  - type: web
    name: careercraft-backend
    env: docker
    plan: free
    repo: https://github.com/Anshulkavi/CareerCraft
    branch: main
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PORT
        value: "8000"
      - key: MONGODB_URI
        value: mongodb+srv://{John}{JohnDoe256}@resumejobf.hm4jqor.mongodb.net/resumejobf?retryWrites=true&w=majority

