services:
  - type: web
    name: careercraft-backend
    env: docker
    plan: free
    repo: https://github.com/Anshulkavi/CareerCraft
    branch: main
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PORT
        value: "8000"
